# Generated by Django 5.2.3 on 2025-06-29 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_tracks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('artist', models.CharField(max_length=300)),
                ('album', models.CharField(blank=True, max_length=300)),
                ('spotify_track_id', models.CharField(blank=True, max_length=100)),
                ('youtube_video_id', models.CharField(blank=True, max_length=50)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('title', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='TransferJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('partial', 'Parcialmente completado')], default='pending', max_length=20)),
                ('youtube_playlist_id', models.CharField(blank=True, max_length=100)),
                ('youtube_playlist_name', models.CharField(blank=True, max_length=200)),
                ('total_songs', models.IntegerField(default=0)),
                ('processed_songs', models.IntegerField(default=0)),
                ('successful_transfers', models.IntegerField(default=0)),
                ('failed_transfers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer.song')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('playlist', 'song', 'position')},
            },
        ),
        migrations.CreateModel(
            name='SongTransferResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Exitoso'), ('failed', 'Fallido'), ('duplicate', 'Duplicado'), ('not_found', 'No encontrado')], max_length=20)),
                ('youtube_video_id', models.CharField(blank=True, max_length=50)),
                ('search_query', models.CharField(max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer.song')),
                ('transfer_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_results', to='transfer.transferjob')),
            ],
            options={
                'unique_together': {('transfer_job', 'song')},
            },
        ),
    ]
