# Generated by Django 5.2.3 on 2025-06-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spotify_display_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
