# Generated by Django 5.2.3 on 2025-06-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_playlist_youtube_playlist_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='spotify_track_id',
            new_name='spotify_id',
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('name', 'artist')},
        ),
        migrations.RemoveField(
            model_name='songtransferresult',
            name='search_query',
        ),
        migrations.RemoveField(
            model_name='songtransferresult',
            name='status',
        ),
        migrations.AddField(
            model_name='song',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='spotify_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='songtransferresult',
            name='match_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='songtransferresult',
            name='transfer_status',
            field=models.CharField(choices=[('success', 'Exitoso'), ('failed', 'Fallido'), ('not_found', 'No encontrado')], default='failed', max_length=20),
        ),
        migrations.AddField(
            model_name='songtransferresult',
            name='youtube_artist',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='songtransferresult',
            name='youtube_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='transferjob',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='songtransferresult',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='songtransferresult',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
