# Generated by Django 5.2.3 on 2025-06-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0004_rename_title_song_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='youtube_music_browser_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube_music_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube_music_configured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
